#!/usr/bin/env bash
set -Eeuo pipefail

formula_path='Formula/alire.rb'

cd "$(cd "$(dirname "$0")" && cd .. && pwd)"

latest_ver=$(curl -fsS https://api.github.com/repos/alire-project/alire/tags | jq -r '[.[].name | select(test("^v[0-9.]+$"))][0]' | tr -d 'v')
cur_ver=$(grep url "$formula_path" | grep -Eo '[0-9]+(\.[0-9]+)+' | tail -1)

if [ "$latest_ver" = "$cur_ver" ]; then
  echo >&2 "alire is already at latest version ($cur_ver)"
  exit 0
fi

set -x

# Update the versions in the url and anywhere else
# Note: Must escape . in sed's regex flavor.
sed -i '' "s/${cur_ver//./\\.}/${latest_ver//./\\.}/g" "$formula_path"

# Update the hash
# TODO rel eng concern: There should be an authoritative and/or cryptographically signed hash available as part of the alire release
download_url=$(sed '/url /!d;s/.*url "//;s/"$//' "$formula_path")
new_hash=$(curl -fsSL "$download_url" | openssl dgst -sha256 | sed 's/.* //')
sed -i '' "s/\\(sha256\\) .*/\\1 \"$new_hash\"/" "$formula_path"

# Release the formula publicly
git commit -am "[version-bump] $latest_ver"
git tag "$latest_ver" -m "$latest_ver"
git push --tags
